### ISSUE TITLE
Future-proof nix support

### ISSUE THREAD

**Issue by rosymati** [UNICT-DMI/faq-dmi-bot#7]
Nix support was introduced with #6, however the current implementation is lacking as it does not pin a specific rust version and is dependent on the version currently used by nixpkgs unstable repo. It also ignores any msrv or rust-toolchain file requiring it to be manually kept in sync with the rest of the project. I am pretty sure the only user is @SingleSlice so it's not an urgent issue but it needs to be fixed nonetheless

**Comment by ghost** [comment]
Wanting to specify that it is not dependant on the user environment, but just the nixpkgs repo most users follow, which will be the unstable one, giving us rustc 1.71.1, this is a devshell and not a deployment shell.

The only fix will be just pinning the nixpkgs repo

**Comment by rosymati** [comment]
> Wanting to specify that it is not dependant on the user environment, but just the nixpkgs repo most users follow, which will be the unstable one, giving us rustc 1.71.1, this is a devshell and not a deployment shell.

I update the issue to reflect that
